### ISSUE TITLE
Wallet is not available at load time in Firefox

### ISSUE THREAD

**Issue by fsodano** [Creit-Tech/xBull-Wallet#1]
Reproducible script:

```<script>
  window.onload = function() {
    console.log(window.xBullSDK);
    setTimeout(() => {
      console.log(window.xBullSDK);
    },100)
  };
</script>```

In chrome you'll see the xBullSDK object twice, in Firefox only the 2nd time.

Digging around, it seems to be related to the `run_at` property for the content scripts. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#run_at

**Comment by earrietadev** [comment]
Aloha! @fsodano, this is the expected behavior because the SDK should be injected after the document has loaded not before (following the default state defined by the browser).

But because you need to access to the SDK at an early moment (as soon as the script loads) we can add an event which you can listen to know when the SDK has been injected.

I will keep this open until the event has been added to the code, it will be added in the next release which is going to be pushed tomorrow.

**Comment by earrietadev** [comment]
@fsodano I just pushed the update that includes the message event to know when the SDK has been injected and a quick explanation here https://xbull.app/developers/#sdk-injected-message

Updated versions were already uploaded to the stores and they should be listed early next week (the stores always take a few days before updating the listed version)

**Comment by fsodano** [comment]
Thank you!
