### ISSUE TITLE
Can't Log Out on Webapp

### ISSUE THREAD

**Issue by Codypinto23** [Creit-Tech/xBull-Wallet#4]
There doesn't seem to be any way to logout from the webapp at the moment. In order to log myself out of the app, I had to go into Chrome's Inspect Elements and manually delete the cookie associated with xBull.

**Comment by earrietadev** [comment]
Hi @Codypinto23, xBull Wallet is a non-custodial wallet which means everything is on your browser and because of that there is no "log in" or "log out" process. Also xBull Wallet does not use cookies or any kind of tracker so if you remove what is in your browser you are actually removing all kind of keys you generated within the wallet.

Let me know if you have more questions

**Comment by Codypinto23** [comment]
@earrietadev Ah, alright, that makes sense! It looks like very major transaction requires your password as well, so in that regard, it's not like someone could just logon to your browser and immediately send XLM out of your account. Cool, thanks!

**Comment by earrietadev** [comment]
@Codypinto23 yeap that's correct your password is always required when signing a transaction because the password is not saved in the browser storage, if you want you can also set a timeout on Settings > Locking Settings > Don't request password. This will keep the password locally in the code for a few minutes (you can select 5, 15 or 30 minutes) or until the page is closed.

If you're ok I will close this issue ticket 😄

**Comment by Codypinto23** [comment]
Sounds good, thanks!
